### PR TITLE
#40: Write center coordinates of a building as an object in json

### PR DESCRIPTION
**Pull request by viveanban**
bug fix, center coordinates were written in the incorrect form in the previous PR for this task

### CODE REVIEW

**Comment by ferdousara-parvin** [comment]
Should we create a bug issue for it?

**Comment by viveanban** [comment]
> Should we create a bug issue for it?

This is not a bug that was introduced from a different issue though. I was created in [my previous PR for this issue](https://github.com/Concordia-Campus-Guide/Concordia-Campus-Guide/pull/127/files?file-filters%5B%5D=.json#diff-130c77a8fceef9d86cab76327df68442):
image

**Comment by ferdousara-parvin** [comment]
> 
> 
> > Should we create a bug issue for it?
> 
> This is not a bug that was introduced from a different issue though. It was created in [my previous PR for this issue](https://github.com/Concordia-Campus-Guide/Concordia-Campus-Guide/pull/127/files?file-filters%5B%5D=.json#diff-130c77a8fceef9d86cab76327df68442):
> image.
> 
> Therefore, I don't think that a bug issue needs to be created for this.

Rightt!

**Comment by viveanban** [comment]
This "bug" has been fixed and merged in another [commit](https://github.com/Concordia-Campus-Guide/Concordia-Campus-Guide/commit/e60a2dc5dfad5f5328d22cb98eee31a578a54cda) as part of [PR#134](https://github.com/Concordia-Campus-Guide/Concordia-Campus-Guide/pull/134).

**Pull request closed without merging**
